name: finance_app
description: Application de gestion financière avec Flutter et Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  intl: ^0.18.1
  fl_chart: ^0.62.0
  provider: ^6.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/